language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7

cache: pip

install:
  - pip install -U pip
  - pip install .[tests]
  - pip install -r requirements_dev.txt

script:
  - coverage run --source=metsaregister -m py.test -v

after_success:
  - codecov
