language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7
matrix:
  allow_failures:
    - python: 2.7

cache: pip

install:
  - pip install -U pip pytest codecov
  - pip install .[test]
  - pip install -r requirements_dev.txt

script:
  - coverage run --source=metsaregister -m py.test -v --vcr-record none

after_success:
  - codecov
